
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed Fixed;

	private global::Gtk.SpinButton SpinButtonMinutes;

	private global::Gtk.Label LabelMinutes;

	private global::Gtk.Button ButtonStartTimer;

	private global::Gtk.Entry EntryMessage;

	private global::Gtk.Label LabelTimeCountDown;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "stock_alarm", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.Fixed = new global::Gtk.Fixed();
		this.Fixed.Name = "Fixed";
		this.Fixed.HasWindow = false;
		// Container child Fixed.Gtk.Fixed+FixedChild
		this.SpinButtonMinutes = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.SpinButtonMinutes.CanFocus = true;
		this.SpinButtonMinutes.Name = "SpinButtonMinutes";
		this.SpinButtonMinutes.Adjustment.PageIncrement = 10D;
		this.SpinButtonMinutes.ClimbRate = 1D;
		this.SpinButtonMinutes.Numeric = true;
		this.SpinButtonMinutes.Value = 5D;
		this.Fixed.Add(this.SpinButtonMinutes);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.Fixed[this.SpinButtonMinutes]));
		w1.X = 101;
		w1.Y = 32;
		// Container child Fixed.Gtk.Fixed+FixedChild
		this.LabelMinutes = new global::Gtk.Label();
		this.LabelMinutes.Name = "LabelMinutes";
		this.LabelMinutes.LabelProp = global::Mono.Unix.Catalog.GetString("Mins");
		this.Fixed.Add(this.LabelMinutes);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.Fixed[this.LabelMinutes]));
		w2.X = 65;
		w2.Y = 36;
		// Container child Fixed.Gtk.Fixed+FixedChild
		this.ButtonStartTimer = new global::Gtk.Button();
		this.ButtonStartTimer.CanFocus = true;
		this.ButtonStartTimer.Name = "ButtonStartTimer";
		this.ButtonStartTimer.UseUnderline = true;
		this.ButtonStartTimer.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.Fixed.Add(this.ButtonStartTimer);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.Fixed[this.ButtonStartTimer]));
		w3.X = 158;
		w3.Y = 134;
		// Container child Fixed.Gtk.Fixed+FixedChild
		this.EntryMessage = new global::Gtk.Entry();
		this.EntryMessage.CanFocus = true;
		this.EntryMessage.Name = "EntryMessage";
		this.EntryMessage.Text = global::Mono.Unix.Catalog.GetString("Brew time!");
		this.EntryMessage.IsEditable = true;
		this.EntryMessage.InvisibleChar = '•';
		this.Fixed.Add(this.EntryMessage);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.Fixed[this.EntryMessage]));
		w4.X = 96;
		w4.Y = 81;
		// Container child Fixed.Gtk.Fixed+FixedChild
		this.LabelTimeCountDown = new global::Gtk.Label();
		this.LabelTimeCountDown.Name = "LabelTimeCountDown";
		this.Fixed.Add(this.LabelTimeCountDown);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.Fixed[this.LabelTimeCountDown]));
		w5.X = 191;
		w5.Y = 213;
		this.Add(this.Fixed);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 347;
		this.DefaultHeight = 263;
		this.LabelTimeCountDown.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ButtonStartTimer.Clicked += new global::System.EventHandler(this.OnStartTimer);
	}
}
